### ISSUE TITLE
Denne borde flyttas til en egen metode

### ISSUE THREAD

**Issue by alexandraback** [navikt/veilarbdirigent#71]
return Try.of(() -> {
            String fnr = aktorService.getFnr(aktorId).get();
            String url = String.format("%s/registrering?fnr=%s", host, fnr);
            return client.target(url).request().get();
        })

**Comment by alexandraback** [comment]
<3

**Comment by alexander-svendsen** [comment]
Koden skal slettes om litt, så tenker vi lar være dette
